--------------------------------------------------------
-- Archivo creado  - sábado-diciembre-20-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "EXAMPLE_API"."CLIENTE" 
   (	"CODCLIENTE" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NRODOC" VARCHAR2(100 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APELLIDO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "EXAMPLE_API"."PRODUCTO" 
   (	"CODPRODUCTO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CODIGOBARRA" VARCHAR2(100 BYTE), 
	"DESPRODUCTO" VARCHAR2(100 BYTE), 
	"PRECIOVENTA" NUMBER(10,2), 
	"STOCK" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VENTA
--------------------------------------------------------

  CREATE TABLE "EXAMPLE_API"."VENTA" 
   (	"CODVENTA" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FECHAVENTA" DATE DEFAULT SYSDATE, 
	"NUMVENTA" VARCHAR2(100 BYTE), 
	"CODCLIENTE" NUMBER, 
	"TOTALVENTA" NUMBER(18,5)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VENTADET
--------------------------------------------------------

  CREATE TABLE "EXAMPLE_API"."VENTADET" 
   (	"CODVENTA" NUMBER, 
	"CODPRODUCTO" NUMBER, 
	"CANTIDADVENTA" NUMBER(18,5), 
	"PRECIOVENTA" NUMBER(18,5), 
	"TOTALLINEA" NUMBER(18,5), 
	"NUMLINEA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into EXAMPLE_API.CLIENTE
SET DEFINE OFF;
Insert into EXAMPLE_API.CLIENTE (CODCLIENTE,NRODOC,NOMBRE,APELLIDO) values ('2','4237259','Enroque','Torales');
Insert into EXAMPLE_API.CLIENTE (CODCLIENTE,NRODOC,NOMBRE,APELLIDO) values ('21','5555666','Prueba','Prueba');
REM INSERTING into EXAMPLE_API.PRODUCTO
SET DEFINE OFF;
Insert into EXAMPLE_API.PRODUCTO (CODPRODUCTO,CODIGOBARRA,DESPRODUCTO,PRECIOVENTA,STOCK) values ('41','23132123','prueba333','2500','10');
Insert into EXAMPLE_API.PRODUCTO (CODPRODUCTO,CODIGOBARRA,DESPRODUCTO,PRECIOVENTA,STOCK) values ('21','12345','pruebax','15000','27');
Insert into EXAMPLE_API.PRODUCTO (CODPRODUCTO,CODIGOBARRA,DESPRODUCTO,PRECIOVENTA,STOCK) values ('61','21324141','Producto Nuevo','1500','3');
REM INSERTING into EXAMPLE_API.VENTA
SET DEFINE OFF;
Insert into EXAMPLE_API.VENTA (CODVENTA,FECHAVENTA,NUMVENTA,CODCLIENTE,TOTALVENTA) values ('22',to_date('20/12/25','DD/MM/RR'),'005','2','48000');
Insert into EXAMPLE_API.VENTA (CODVENTA,FECHAVENTA,NUMVENTA,CODCLIENTE,TOTALVENTA) values ('21',to_date('20/12/25','DD/MM/RR'),'55555','2','7500');
REM INSERTING into EXAMPLE_API.VENTADET
SET DEFINE OFF;
Insert into EXAMPLE_API.VENTADET (CODVENTA,CODPRODUCTO,CANTIDADVENTA,PRECIOVENTA,TOTALLINEA,NUMLINEA) values ('22','21','3','15000','45000','1');
Insert into EXAMPLE_API.VENTADET (CODVENTA,CODPRODUCTO,CANTIDADVENTA,PRECIOVENTA,TOTALLINEA,NUMLINEA) values ('22','61','2','1500','3000','2');
Insert into EXAMPLE_API.VENTADET (CODVENTA,CODPRODUCTO,CANTIDADVENTA,PRECIOVENTA,TOTALLINEA,NUMLINEA) values ('21','61','5','1500','7500','1');
--------------------------------------------------------
--  DDL for Procedure SP_ACTUALIZAR_CLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "EXAMPLE_API"."SP_ACTUALIZAR_CLIENTE" (
    p_codcliente IN NUMBER,
    p_nrodoc     IN VARCHAR2,
    p_nombre     IN VARCHAR2,
    p_apellido   IN VARCHAR2
)
AS
    v_count NUMBER;
BEGIN
    -- Validar documento duplicado
    SELECT COUNT(*)
    INTO v_count
    FROM cliente
    WHERE nrodoc = p_nrodoc
      AND codcliente <> p_codcliente;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20010,
            'Ya existe un cliente con este número de documento'
        );
    END IF;

    -- Actualizar cliente
    UPDATE cliente
    SET nombre   = p_nombre,
        apellido = p_apellido,
        nrodoc   = p_nrodoc
    WHERE codcliente = p_codcliente;

END SP_ACTUALIZAR_CLIENTE;

/
--------------------------------------------------------
--  DDL for Procedure SP_ACTUALIZAR_PRODUCTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "EXAMPLE_API"."SP_ACTUALIZAR_PRODUCTO" (
    p_codproducto   IN NUMBER,
    p_codigobarra   IN VARCHAR2,
    p_desproducto   IN VARCHAR2,
    p_precioventa  IN NUMBER,
    p_stock         IN NUMBER
)
IS
    v_count NUMBER;
BEGIN
    -- Validar código de barra duplicado
    SELECT COUNT(*) INTO v_count
    FROM producto
    WHERE codigobarra = p_codigobarra
      AND codproducto <> p_codproducto;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20030,
            'Ya existe otro producto con ese código de barra'
        );
    END IF;

    -- Actualizar producto
    UPDATE producto
    SET desproducto  = p_desproducto,
        precioventa  = p_precioventa,
        stock        = p_stock
    WHERE codproducto = p_codproducto;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20031,
            'No se encontró el producto a actualizar'
        );
    END IF;
END;

/
--------------------------------------------------------
--  DDL for Procedure SP_ACTUALIZAR_VENTA_DET
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "EXAMPLE_API"."SP_ACTUALIZAR_VENTA_DET" (
    p_codventa    IN NUMBER,
    p_codproducto IN NUMBER,
    p_cantidad    IN NUMBER,
    p_precio      IN NUMBER
)
AS
    v_stock NUMBER;
    v_maxlinea NUMBER;
BEGIN
    -- Bloquea producto y valida stock
    SELECT stock
    INTO v_stock
    FROM producto
    WHERE codproducto = p_codproducto
    FOR UPDATE;

    IF p_cantidad > v_stock THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Stock insuficiente para el producto ' || p_codproducto ||
            '. Stock disponible: ' || v_stock
        );
    END IF;

    -- Número de línea
    SELECT NVL(MAX(numlinea), 0) + 1
    INTO v_maxlinea
    FROM ventadet
    WHERE codventa = p_codventa;

    -- Insertar detalle
    INSERT INTO ventadet (
        codventa,
        codproducto,
        cantidadventa,
        precioventa,
        totallinea,
        numlinea
    )
    VALUES (
        p_codventa,
        p_codproducto,
        p_cantidad,
        p_precio,
        p_cantidad * p_precio,
        v_maxlinea
    );

    -- Descontar stock
    UPDATE producto
    SET stock = stock - p_cantidad
    WHERE codproducto = p_codproducto;

    --Recalcular total desde el detalle
    UPDATE venta
    SET totalventa = (
        SELECT NVL(SUM(totallinea), 0)
        FROM ventadet
        WHERE codventa = p_codventa
    )
    WHERE codventa = p_codventa;
END SP_ACTUALIZAR_VENTA_DET;

/
--------------------------------------------------------
--  DDL for Procedure SP_ELIMINAR_CLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "EXAMPLE_API"."SP_ELIMINAR_CLIENTE" (
    p_codcliente IN NUMBER
)
AS
    v_count NUMBER;
BEGIN
    -- Validar que exista el cliente
    SELECT COUNT(*)
    INTO v_count
    FROM cliente
    WHERE codcliente = p_codcliente;

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20020,
            'No se encontró el cliente a eliminar'
        );
    END IF;

    -- Validar que no tenga ventas asociadas
    SELECT COUNT(*)
    INTO v_count
    FROM venta
    WHERE codcliente = p_codcliente;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20021,
            'No se puede eliminar el cliente porque tiene ventas asociadas'
        );
    END IF;

    -- Eliminar cliente
    DELETE FROM cliente
    WHERE codcliente = p_codcliente;

END SP_ELIMINAR_CLIENTE;

/
--------------------------------------------------------
--  DDL for Procedure SP_ELIMINAR_PRODUCTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "EXAMPLE_API"."SP_ELIMINAR_PRODUCTO" (
    p_codproducto IN NUMBER
)
IS
    v_count NUMBER;
BEGIN
    -- Validar existencia
    SELECT COUNT(*) INTO v_count
    FROM producto
    WHERE codproducto = p_codproducto;

    IF v_count = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20040,
            'No se encontró el producto a eliminar'
        );
    END IF;

    -- Validar que no esté usado en ventas
    SELECT COUNT(*) INTO v_count
    FROM ventadet
    WHERE codproducto = p_codproducto;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20041,
            'No se puede eliminar el producto porque tiene ventas asociadas'
        );
    END IF;

    -- Eliminar producto
    DELETE FROM producto
    WHERE codproducto = p_codproducto;
END;

/
--------------------------------------------------------
--  DDL for Procedure SP_ELIMINAR_VENTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "EXAMPLE_API"."SP_ELIMINAR_VENTA" (
    p_codventa IN NUMBER
)
AS
BEGIN
    --Devolver stock de los productos
    FOR rec IN (
        SELECT codproducto, cantidadventa
        FROM ventadet
        WHERE codventa = p_codventa
    ) LOOP
        UPDATE producto
        SET stock = stock + rec.cantidadventa
        WHERE codproducto = rec.codproducto;
    END LOOP;

    --Eliminar detalle
    DELETE FROM ventadet
    WHERE codventa = p_codventa;

    --Eliminar cabecera
    DELETE FROM venta
    WHERE codventa = p_codventa;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_ELIMINAR_VENTA;

/
--------------------------------------------------------
--  DDL for Procedure SP_INSERTAR_CLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "EXAMPLE_API"."SP_INSERTAR_CLIENTE" (
    p_nrodoc IN CLIENTE.NRODOC%TYPE,
    p_nombre IN CLIENTE.NOMBRE%TYPE,
    p_apellido IN CLIENTE.APELLIDO%TYPE
)
IS
    v_count NUMBER;
BEGIN
    -- Validación: que no exista un cliente con el mismo nro de documento
    SELECT COUNT(*) INTO v_count
    FROM CLIENTE
    WHERE NRODOC = p_nrodoc;
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ya existe un cliente con el nro documento a registrar.');
    END IF;

    -- Validación: de los campos de nombre y apellido
    IF TRIM(p_nombre) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20002, 'El nombre del cliente no puede estar vacío.');
    END IF;

    IF TRIM(p_apellido) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20002, 'El nombre del cliente no puede estar vacío.');
    END IF;

    INSERT INTO CLIENTE (nrodoc, nombre, apellido)
    VALUES (p_nrodoc, p_nombre, p_apellido);    
    COMMIT;
END sp_insertar_cliente;

/
--------------------------------------------------------
--  DDL for Procedure SP_INSERTAR_PRODUCTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "EXAMPLE_API"."SP_INSERTAR_PRODUCTO" (
    p_codigobarra IN PRODUCTO.CODIGOBARRA%TYPE,
    p_desproducto IN PRODUCTO.DESPRODUCTO%TYPE,
    p_precioventa IN PRODUCTO.PRECIOVENTA%TYPE,
    p_stock IN PRODUCTO.STOCK%TYPE
)
IS
    v_count NUMBER;
BEGIN
    -- Validación: que no exista el código de barra
    SELECT COUNT(*) INTO v_count
    FROM PRODUCTO
    WHERE CODIGOBARRA = p_codigobarra;
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ya existe un producto con ese código de barra.');
    END IF;

    -- Validación: descripción no vacía
    IF TRIM(p_desproducto) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20002, 'La descripción del producto no puede estar vacía.');
    END IF;

    INSERT INTO PRODUCTO (CODIGOBARRA, DESPRODUCTO, PRECIOVENTA, STOCK)
    VALUES (p_codigobarra, p_desproducto, p_precioventa, p_stock);    
    COMMIT;
END sp_insertar_producto;

/
--------------------------------------------------------
--  DDL for Procedure SP_INSERTAR_VENTA_CAB
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "EXAMPLE_API"."SP_INSERTAR_VENTA_CAB" (
    p_numventa IN VARCHAR2,
    p_codcliente IN NUMBER,
    p_codventa_out OUT NUMBER
)
AS
BEGIN
    INSERT INTO venta(numventa, codcliente, totalventa)
    VALUES(p_numventa, p_codcliente, 0)
    RETURNING codventa INTO p_codventa_out;
END SP_INSERTAR_VENTA_CAB;

/
--------------------------------------------------------
--  DDL for Procedure SP_INSERTAR_VENTA_DET
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "EXAMPLE_API"."SP_INSERTAR_VENTA_DET" (
    p_codventa IN NUMBER,
    p_codproducto IN NUMBER,
    p_cantidad IN NUMBER,
    p_precio IN NUMBER
)
AS
    v_stock NUMBER;
    v_maxlinea NUMBER;
BEGIN
    -- Bloquea el producto para evitar conflictos y valida stock
    SELECT stock INTO v_stock
    FROM producto
    WHERE codproducto = p_codproducto
    FOR UPDATE;

    IF p_cantidad > v_stock THEN
        RAISE_APPLICATION_ERROR(-20001, 
            'No hay stock suficiente para el producto ' || p_codproducto || 
            '. Stock disponible: ' || v_stock);
    END IF;

    -- Obtener el siguiente número de línea
    SELECT NVL(MAX(numlinea), 0) + 1 INTO v_maxlinea
    FROM ventadet
    WHERE codventa = p_codventa;

    -- Insertar detalle
    INSERT INTO ventadet(codventa, codproducto, cantidadventa, precioventa, totallinea, numlinea)
    VALUES(p_codventa, p_codproducto, p_cantidad, p_precio, p_cantidad * p_precio, v_maxlinea);

    -- Descontar stock
    UPDATE producto
    SET stock = stock - p_cantidad
    WHERE codproducto = p_codproducto;
END SP_INSERTAR_VENTA_DET;

/
--------------------------------------------------------
--  DDL for Procedure SP_LIMPIAR_DETALLE_VENTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "EXAMPLE_API"."SP_LIMPIAR_DETALLE_VENTA" (
    p_codventa IN NUMBER
)
AS
BEGIN
    -- Devolver stock
    FOR r IN (
        SELECT codproducto, cantidadventa
        FROM ventadet
        WHERE codventa = p_codventa
    ) LOOP
        UPDATE producto
        SET stock = stock + r.cantidadventa
        WHERE codproducto = r.codproducto;
    END LOOP;

    -- Borrar detalle
    DELETE FROM ventadet
    WHERE codventa = p_codventa;
END SP_LIMPIAR_DETALLE_VENTA;

/
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "EXAMPLE_API"."CLIENTE" MODIFY ("CODCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "EXAMPLE_API"."CLIENTE" ADD PRIMARY KEY ("CODCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "EXAMPLE_API"."VENTA" MODIFY ("CODVENTA" NOT NULL ENABLE);
  ALTER TABLE "EXAMPLE_API"."VENTA" MODIFY ("CODCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "EXAMPLE_API"."VENTA" ADD PRIMARY KEY ("CODVENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "EXAMPLE_API"."PRODUCTO" MODIFY ("CODPRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "EXAMPLE_API"."PRODUCTO" MODIFY ("PRECIOVENTA" NOT NULL ENABLE);
  ALTER TABLE "EXAMPLE_API"."PRODUCTO" MODIFY ("STOCK" NOT NULL ENABLE);
  ALTER TABLE "EXAMPLE_API"."PRODUCTO" ADD PRIMARY KEY ("CODPRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VENTADET
--------------------------------------------------------

  ALTER TABLE "EXAMPLE_API"."VENTADET" MODIFY ("CODVENTA" NOT NULL ENABLE);
  ALTER TABLE "EXAMPLE_API"."VENTADET" MODIFY ("CODPRODUCTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "EXAMPLE_API"."VENTA" ADD CONSTRAINT "FK_VENTA_CLIENTE" FOREIGN KEY ("CODCLIENTE")
	  REFERENCES "EXAMPLE_API"."CLIENTE" ("CODCLIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENTADET
--------------------------------------------------------

  ALTER TABLE "EXAMPLE_API"."VENTADET" ADD CONSTRAINT "FK_VENTADET_VENTA" FOREIGN KEY ("CODVENTA")
	  REFERENCES "EXAMPLE_API"."VENTA" ("CODVENTA") ENABLE;
  ALTER TABLE "EXAMPLE_API"."VENTADET" ADD CONSTRAINT "FK_VENTADET_PRODUCTO" FOREIGN KEY ("CODPRODUCTO")
	  REFERENCES "EXAMPLE_API"."PRODUCTO" ("CODPRODUCTO") ENABLE;
